# Configuration file for yamllint.
# It extends the default conf by adjusting some options.
extends: default

rules:
    # No document start '---' missing warnings.
    document-start: disable

    # 132 chars should be enough, so fail if a line is longer.
    line-length:
        max: 132
        level: error
