name: ci-commit-cycle
    # Continuous Delivery (CD): Testing Strategy for DevOps: Commit Cyle, Acceptance Cycle, Release Cycle, Product Cycle.
    #   Commit Cycle: Unit Test, Coding Standards Asserted, Common Error Detection.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'FastingReporter', destination: 'platform=iOS Simulator,OS=14.4,name=iPhone 8', testPlan: 'CommitCycle_iOS' }

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    #- name: Homebrew build helpers install
      #run: brew bundle

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

    - name: Show what's in Applications
      run: ls -al /Applications

    #- name: Switch to Xcode 12
      #run: sudo xcode-select -s /Applications/Xcode_12.5.1.app

    - name: Show Build Version
      run: xcodebuild -version
      
    - name: Show Build Settings
      run: xcodebuild -project FastingReporter.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings
      #run: xcodebuild -project FastingReporter.xcodeproj -scheme 'FastingReporter' -showBuildSettings

    - name: Show Build SDK
      run: xcodebuild -project FastingReporter.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -showsdks

    - name: Show Available Destinations
      run: xcodebuild -project FastingReporter.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

    - name: Show SwiftLint Version
      run: swiftlint version
      
    - name: Run SwiftLint
      run: swiftlint lint
      #run: swift format lint --configuration .swift-format-config -r .

    - name: Build and Commit Cycle Test per Config Matrix
      run: |
        xcodebuild clean test \
            -project FastingReporter.xcodeproj \
            -scheme '${{ matrix.run-config['scheme'] }}' \
            -destination '${{ matrix.run-config['destination'] }}' \
            -testPlan '${{ matrix.run-config['testPlan'] }}' \
            -showBuildTimingSummary
